export const PRESETS = [
  {
    id: 'retrowave-pale-blue',
    name: 'RETROWAVE PALE BLUE',
    description: 'Hero benchmark preset: pale cyan skin shift, neon magenta/cyan presentation and graphic cel contrast.',
    defaults: { styleStrength: 70, detail: 65, contrast: 80, glow: 55, edgeClean: 60, skinToneLock: 75, backgroundBlend: 40 },
    render: { hue: 190, saturation: 1.25, contrast: 1.15, ink: 1.0, posterLevels: 10, cyanWash: 0.16, magentaWash: 0.22 }
  },
  {
    id: 'adobe-neon-noir',
    name: 'ADOBE NEON NOIR',
    description: 'New game benchmark: illustrated neon-noir horror with emerald/cyan practical light, hot magenta backlight, deep black shadow shapes, textured surfaces and cinematic corridor depth.',
    defaults: { styleStrength: 84, detail: 78, contrast: 88, glow: 64, edgeClean: 76, skinToneLock: 82, backgroundBlend: 66 },
    render: { hue: 285, saturation: 1.5, contrast: 1.34, ink: 1.32, posterLevels: 9, cyanWash: 0.13, magentaWash: 0.3 }
  },
  {
    id: 'crimson-minimum',
    name: 'CRIMSON MINIMUM',
    description: 'Minimal crimson-and-black graphic treatment with hard shadow separation, restrained glow and simplified colour planes.',
    defaults: { styleStrength: 78, detail: 46, contrast: 90, glow: 28, edgeClean: 88, skinToneLock: 72, backgroundBlend: 34 },
    render: { hue: 338, saturation: 1.42, contrast: 1.42, ink: 1.4, posterLevels: 5, cyanWash: 0, magentaWash: 0.2 }
  },
  {
    id: 'emerald',
    name: 'EMERALD',
    description: 'Dark emerald game-art treatment with cool green light, dense shadows and controlled neon energy.',
    defaults: { styleStrength: 76, detail: 70, contrast: 82, glow: 50, edgeClean: 70, skinToneLock: 84, backgroundBlend: 56 },
    render: { hue: 132, saturation: 1.35, contrast: 1.28, ink: 1.16, posterLevels: 9, cyanWash: 0.1, magentaWash: 0.02 }
  },
  {
    id: 'noir-ink',
    name: 'NOIR INK',
    description: 'High-contrast monochrome comic treatment inspired by the rollback comic-ink stage.',
    defaults: { styleStrength: 82, detail: 70, contrast: 90, glow: 4, edgeClean: 84, skinToneLock: 100, backgroundBlend: 22 },
    render: { hue: 0, saturation: 0, contrast: 1.58, ink: 1.5, posterLevels: 6, cyanWash: 0, magentaWash: 0 }
  },
  {
    id: 'neon-comic',
    name: 'NEON COMIC',
    description: 'Stronger magenta/cyan comic treatment with deliberately graphic shadow masses.',
    defaults: { styleStrength: 84, detail: 60, contrast: 84, glow: 72, edgeClean: 67, skinToneLock: 58, backgroundBlend: 48 },
    render: { hue: 310, saturation: 1.62, contrast: 1.27, ink: 1.1, posterLevels: 8, cyanWash: 0.1, magentaWash: 0.3 }
  },
  {
    id: 'soft-portrait',
    name: 'SOFT PORTRAIT',
    description: 'Lower line strength with warmer colour retention and gentler tonal simplification.',
    defaults: { styleStrength: 45, detail: 82, contrast: 54, glow: 20, edgeClean: 38, skinToneLock: 92, backgroundBlend: 72 },
    render: { hue: 18, saturation: 1.04, contrast: 1.02, ink: 0.32, posterLevels: 14, cyanWash: 0.02, magentaWash: 0.04 }
  },
  {
    id: 'clean-vector',
    name: 'CLEAN VECTOR',
    description: 'Simplified colour planes with stronger contour cleanup and restrained texture.',
    defaults: { styleStrength: 68, detail: 48, contrast: 76, glow: 16, edgeClean: 92, skinToneLock: 82, backgroundBlend: 38 },
    render: { hue: 205, saturation: 1.14, contrast: 1.3, ink: 1.24, posterLevels: 5, cyanWash: 0.08, magentaWash: 0.05 }
  },
  {
    id: 'custom-ai',
    name: 'CUSTOM AI PRESET',
    description: 'Schema-valid custom preset generated by AI Assist or edited later by the user.',
    defaults: { styleStrength: 70, detail: 70, contrast: 72, glow: 42, edgeClean: 66, skinToneLock: 82, backgroundBlend: 50 },
    render: { hue: 260, saturation: 1.3, contrast: 1.2, ink: 0.9, posterLevels: 9, cyanWash: 0.1, magentaWash: 0.12 }
  }
];

export const CONTROL_DEFS = [
  ['styleStrength', 'Style Strength'],
  ['detail', 'Detail'],
  ['contrast', 'Contrast'],
  ['glow', 'Glow'],
  ['edgeClean', 'Edge Clean'],
  ['skinToneLock', 'Skin Tone Lock'],
  ['backgroundBlend', 'Background Blend']
];

export function getPreset(id) {
  return PRESETS.find((preset) => preset.id === id) || PRESETS[0];
}
